### ISSUE TITLE
Gesture is Chromium-specific jargon; the web-developer facing term is "user activation"

### ISSUE THREAD

**Issue by domenic** [WICG/gesture-delegation#2]
To match other platform APIs that expose this concept (such as iframe sandbox), the attribute should be allowuseractivationdelegation.

**Comment by annevk** [comment]
Maybe just `allowuseractivation`? That seems more consistent with `allowfullscreen` and `allowpaymentrequest`.

**Comment by domenic** [comment]
The issue is that (as per #4) it's not actually about allowing user activation. It's about allowing delegation of user activation, which in turn allows other features like fullscreen.

Figuring out #4 though is a bit of a blocker, especially with regard to your comment at https://github.com/WICG/gesture-delegation/issues/4#issuecomment-331864409

**Comment by mustaqahmed** [comment]
@domenic, it seems to me that request #3 handled this issue.  In particular, `allowedActivationDelegation` looks like a what you preferred above.  May be we can close this issue?

**Comment by annevk** [comment]
No, "allowed" is wrong. It needs to be "allow" to be consistent.

**Comment by jyasskin** [comment]
Well, "allowed"->"allow" is a different issue than "gesture"->"activation", so I've filed it as #6.

**Comment by annevk** [comment]
That issue fails to capture something else I just noticed, that "user" somehow got dropped, even though as OP points out we already use that in identifiers.

**Comment by mmoss** [comment]
Has this been implemented yet, and if so which builds can we find it in? I wasn't able to use this in the latest version of Canary, which was surprising, since was referenced by the [Autoplay Policy Changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#iframe). If this is purely proposal (i.e. not implemented yet), how should someone proceed to test the latest policy changes in Canary (and work around them without this API)?
