### ISSUE TITLE
origin vs. domain

### ISSUE THREAD

**Issue by domenic** [WICG/gesture-delegation#9]
> outside of the current domain.

I don't know what "current domain" is defined as, technically. eTLD+1 is a concept I don't understand but at least have seen in specs; "domain" is not (apart from document.domain).

It seems better to be stricter and restrict to origin, anyway.

**Comment by mounirlamouri** [comment]
I meant eTLD+1. We picked eTLD+1 for the moment because in the context of autoplay, we believe that this is less likely to break websites and we don't want websites to change their architecture. This is not a security feature so origin isn't mandatory. I think we would like to move to origin for consistency later based on how things go.
